import { StyleSheet } from '@react-pdf/renderer'

export const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, fontFamily: 'Helvetica', color: '#1a1a1a' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 14,
    borderBottomWidth: 1, borderBottomColor: '#333', paddingBottom: 10 },
  empresa: { fontSize: 16, fontFamily: 'Helvetica-Bold' },
  empresaSub: { fontSize: 8, color: '#666', marginTop: 2 },
  docTitulo: { fontSize: 13, fontFamily: 'Helvetica-Bold', textAlign: 'right' },
  docMeta: { fontSize: 8, color: '#444', textAlign: 'right', marginTop: 2 },
  destinatario: { marginBottom: 12 },
  etiqueta: { fontSize: 7, color: '#888', textTransform: 'uppercase' },
  destNombre: { fontSize: 11, fontFamily: 'Helvetica-Bold', marginTop: 1 },
  avisoIncompleto: { backgroundColor: '#fbeaea', borderWidth: 1, borderColor: '#c0392b',
    padding: 8, marginBottom: 12, borderRadius: 3 },
  avisoIncompletoTxt: { color: '#c0392b', fontFamily: 'Helvetica-Bold', fontSize: 9 },
  avisoIncompletoSub: { color: '#a03024', fontSize: 7.5, marginTop: 2 },
  thead: { flexDirection: 'row', backgroundColor: '#f0f0f0', borderBottomWidth: 1,
    borderBottomColor: '#ccc', paddingVertical: 4 },
  row: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: '#e0e0e0',
    paddingVertical: 4, alignItems: 'flex-start' },
  th: { fontSize: 7.5, fontFamily: 'Helvetica-Bold', color: '#555', paddingHorizontal: 3 },
  td: { fontSize: 8.5, paddingHorizontal: 3 },
  cNum: { width: '5%' },
  cDesc: { width: '39%' },
  cUbi: { width: '13%' },
  cMed: { width: '13%' },
  cCant: { width: '7%', textAlign: 'right' },
  cPrecio: { width: '11%', textAlign: 'right' },
  cImporte: { width: '12%', textAlign: 'right' },
  sinValorar: { color: '#c0392b', fontFamily: 'Helvetica-Oblique' },
  aviso: { fontSize: 7, color: '#b8860b', marginTop: 1 },
  totales: { marginTop: 14, alignSelf: 'flex-end', width: '45%' },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 2 },
  totalRowFinal: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4,
    borderTopWidth: 1, borderTopColor: '#333', marginTop: 3 },
  totalLbl: { fontSize: 9, color: '#444' },
  totalVal: { fontSize: 9 },
  totalFinalLbl: { fontSize: 11, fontFamily: 'Helvetica-Bold' },
  totalFinalVal: { fontSize: 11, fontFamily: 'Helvetica-Bold' },
  pie: { position: 'absolute', bottom: 24, left: 36, right: 36, fontSize: 6.5,
    color: '#999', textAlign: 'center', borderTopWidth: 0.5, borderTopColor: '#ddd', paddingTop: 4 },
})
